src/main/java/shuai2/entity/Book.java
package shuai2.entity;

public class Book {
	private String isbn;
	private String name;
	private double price; 
	
	public String[] getAllBooks(){
		String[] books={"java","c","c++"};
		return books;
	}
	
	public Book() {
	}

	public Book(String isbn, String name, double price) {
		this.isbn = isbn;
		this.name = name;
		this.price = price;
	}

	public String getIsbn() {
		return isbn;
	}
	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public double getPrice() {
		return price;
	}
	public void setPrice(double price) {
		this.price = price;
	}
	
}

src/main/java/shuai2/entity/OgnlInfo.java
package shuai2.entity;

public class OgnlInfo {
	public String sayHello(String name){
		return name+"你好";
	}
	public static String sayBey(String name){
		return name+"再见";
	}
}

src/main/java/shuai2/entity/User.java
package shuai2.entity;

public class User {
	private String username;
	private String password;
	private String contry;
	private String role;
	
	public String getContry() {
		return contry;
	}
	public void setContry(String contry) {
		this.contry = contry;
	}
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getRole() {
		return role;
	}
	public void setRole(String role) {
		this.role = role;
	}
}

src/main/java/shuai2/action/LoginAction.java
package shuai2.action;

import com.opensymphony.xwork2.ActionContext;

import shuai2.entity.User;

public class LoginAction extends BaseAction {
	private User user;
	
	public String execute(){
		/*ActionContext.getContext().put("username", "lisi");
		getMapRequest().put("username", "wangwu");*/
		return SUCCESS;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
	
	
	
}

src/main/webapp/book.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@taglib uri="/struts-tags" prefix="s"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
	<!-- 实例化一个book javabean对象，并存储到stackContext中 -->
	<s:bean id="book" name="shuai2.entity.Book">
		<!-- 为book对象的isbn赋值 -->
		<s:param name="isbn" value="123455"/>
		<!-- 为book对象的name赋值 -->
		<s:param name="name" value="Html"/>
	</s:bean>
	book对象的属性值：<br/>
	isbn:<s:property value="#book.isbn"/>
	name:<s:property value="#book.name"/>
	调用book对象的getAllBooks方法获取全部书籍列表：<br/>
	<c:forEach var="book" items="${book.allBooks }">
		<li>${book }</li>	
	</c:forEach>
	<br/>
	
	
	<s:bean id="today" name="java.util.Date"/>
	<h3>
		今天是：<s:date name="#today" format="yyyy年MM月dd日"/>
	</h3>
</body>
</html>

src/main/webapp/index.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="/struts-tags" prefix="s" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
	<%-- ValueStack里面的值：<s:property value="username"/><br/>
	ActionStack里面的值：<s:property value="#username"/><br/>
	StackContext里面的值：<s:property value="#attr.username"/><br/>
	StackContext里面的值：<s:property value="#request.username"/> --%>
	
	用户名&nbsp;：<s:property value="user.username"/><br/>
	所在城市：<s:property value="user.contry"/><br/>
	选择权限是：<s:property value="user.role"/>
</body>
</html>

src/main/webapp/login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
	<form action="login" method="post">
		账号：<input type="text" name="user.username"/><br/>
		密码：<input type="password" name="user.password"/><br>
		城市：<input type="text" name="user.contry"/><br/>
		<input type="submit" value="提交"/>
	</form>
</body>
</html>

src/main/webapp/mapBook.jsp
<%@page import="shuai2.entity.Book"%>
<%@page import="java.util.HashMap"%>
<%@page import="java.util.Map"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@taglib uri="/struts-tags" prefix="s"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
	<%
		Map<String,Object> maps=new HashMap<String,Object>();
		Book b1=new Book("11","gfdsa",122);
		Book b2=new Book("12","gfdsa1",1221);
		Book b3=new Book("13","gfdsa2",1222);
		//把b1，b2，b3的isbn作为键值，他们自己作为值
		maps.put(b1.getIsbn(), b1);
		maps.put(b2.getIsbn(), b2);
		maps.put(b3.getIsbn(), b3);
		request.setAttribute("maps", maps);
	%>
	<s:iterator id="book" value="#attr.maps">
		<!-- book.key是maps的键，book.value是maps的值即b1 b2 b3 -->
		<s:property value="#book.key"/>
		<s:property value="#book.value.name"/>
		<s:property value="#book.value.price"/>
		<br/>
	</s:iterator>
	
</body>
</html>

src/main/webapp/ognl.jsp
<%@page import="shuai2.entity.OgnlInfo"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    <%@taglib uri="/struts-tags" prefix="s" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
	<% OgnlInfo ognlInfo=new OgnlInfo();
		request.setAttribute("ognlInfo", ognlInfo);
	%>
	<!-- 执行OGNL的费静态方法 -->
	<s:property value="#attr.ognlInfo.sayHello('kognshuai')"/>
	<s:property value="@shuai2.entity.OgnlInfo@sayBey('kongshuai')"/>
</body>
</html>

src/main/webapp/submit.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@taglib uri="/struts-tags" prefix="s"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
	<%
		String title = "提交";
		request.setAttribute("title", title);
	%>

	<%-- <s:submit value="%{#attr.title}"/>
	<s:if test="'java' in {'java','c'}">
		在里面
		<s:else>
			不在里面
		</s:else>
	</s:if> --%>

	<s:form action="login">
		<s:select list="#{'1':'管理员','2':'普通员工','3':'店长' }" listKey="key"
			listValue="value" name="user.role" />
		<s:submit value="%{#attr.title }"/>
	</s:form>



</body>
</html>

src/main/webapp/tableBook.jsp
<%@page import="java.util.ArrayList"%>
<%@page import="shuai2.entity.Book"%>
<%@page import="java.util.List"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@taglib uri="/struts-tags" prefix="s"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
	<%
		List<Book> books=new ArrayList<Book>();
		Book b1=new Book();
		b1.setIsbn("111");
		b1.setName("kong");
		b1.setPrice(11111);
		
		Book b2=new Book();
		b2.setIsbn("1111");
		b2.setName("konga");
		b2.setPrice(11111111);
		
		Book b3=new Book();
		b3.setIsbn("111qw");
		b3.setName("kongre");
		b3.setPrice(11111453);
		
		books.add(b1);
		books.add(b2);
		books.add(b3);
		request.setAttribute("books", books);
	%>
	
	<table>
		<s:iterator id="book" value="#attr.books" status="st">
			<s:if test="#st.odd">
				<tr bgcolor="yellow">
			</s:if>
			<s:else >
				<tr bgcolor="blue">
			</s:else>
			<td><s:property value="#book.name"/></td>
			<td><s:property value="#book.isbn"/></td>
			<td><s:property value="#book.price"/></td>
		</s:iterator>
	</table>
</body>
</html>